[project]
authors = [
    { name = "Benjamin Bogenberger", email = "benjamin.bogenberger@tum.de" },
]
dependencies = ["pyb-utils>=2.4.2,<3", "xacrodoc>=1.3.1,<2", "ompl>=2.0.1,<3"]
name = "mobile_manipulation"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["robostack-humble", "conda-forge", "nvidia"]
platforms = ["linux-64"]

[tool.pixi.tasks]
# build = { cmd = "..."}

[tool.pixi.dependencies]
spatialmath-python = ">=1.1.15,<2"
pybullet = ">=3.25,<4"
casadi = ">=3.7.0,<4"
liecasadi = ">=0.0.7,<0.0.8"
holoviews = ">=1.22.1,<2"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=82.0.0,<83"
numpy = ">=1.26.4,<2"
scipy = ">=1.17.0,<2"
xacro = ">=2.1.1,<3"
yaml = ">=0.2.5,<0.3"
pinocchio = ">=3.7.0,<4"
pip = ">=26.0.1,<27"
ros-humble-tf-transformations = ">=1.1.0,<2"
transforms3d = "*"
jax = ">=0.7.0,<0.8"
jaxlib = ">=0.7.0,<0.8"
jaxlie = ">=1.5.0,<2"
glib = ">=2.86.2,<3"
libgl = ">=1.7.0,<2"
cuda-nvcc = ">=12.9.86,<13"
libnpp = "*"

[tool.pixi.pypi-dependencies]
torch = { version = "<=2.9.1", index = "https://download.pytorch.org/whl/cu128" }
# if error do "export UV_SKIP_WHEEL_FILENAME_CHECK=1"
nvblox-torch = { url = "https://github.com/nvidia-isaac/nvblox/releases/download/v0.0.10/nvblox_torch-0.0.10+cu12ubuntu24-py3-none-linux_x86_64.whl"}

[tool.pixi.activation]
scripts = ["install/setup.sh", "tools/setup_acados.sh"]

[tool.pixi.activation.env]
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

[tool.pixi.system-requirements]
cuda = "12.8"
