simulation:
  timestep: 0.03
  gravity: [0, 0, 0]
  static_obstacles:
    enabled: true

include:
  - package: "mm_run"
    path: "config/scene/aws_small_warehouse.yaml"

logging:
  log_dir: "aws_small_warehouse_env_esdf"
  log_level: 20
