import argparse
import os
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import matplotlib.pyplot as plt
import numpy as np


def save_esdf_image(path, xs, ys, data, valid, title, max_abs_distance):
    masked = np.ma.masked_where(~valid, data)
    fig, ax = plt.subplots(figsize=(8, 6), constrained_layout=True)
    im = ax.imshow(
        masked.T,
        origin="lower",
        extent=[float(xs[0]), float(xs[-1]), float(ys[0]), float(ys[-1])],
        cmap="coolwarm_r",
        vmin=-max_abs_distance,
        vmax=max_abs_distance,
        interpolation="nearest",
    )
    ax.set_title(title)
    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.set_aspect("equal")
    fig.colorbar(im, ax=ax, label="signed distance [m]")
    fig.savefig(path, dpi=160)
    plt.close(fig)


def export_base_navigation_esdf(
    input_path,
    output_dir,
    z_min,
    z_max,
    inflation_radius,
    max_abs_distance,
):
    data = np.load(input_path)
    xs = data["xs"]
    ys = data["ys"]
    zs = data["zs"]
    distances = data["distance"]
    valid = data["valid"]

    z_mask = (zs >= z_min) & (zs <= z_max)
    if not np.any(z_mask):
        raise ValueError(
            f"z band [{z_min}, {z_max}] does not overlap grid range "
            f"[{float(zs[0])}, {float(zs[-1])}]"
        )

    projected = np.min(
        np.where(valid[:, :, z_mask], distances[:, :, z_mask], np.inf),
        axis=2,
    )
    projected_valid = np.isfinite(projected)
    inflated = projected - float(inflation_radius)

    output_dir.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output_dir / "base_navigation_esdf.npz",
        xs=xs,
        ys=ys,
        z_min=np.asarray(z_min, dtype=np.float32),
        z_max=np.asarray(z_max, dtype=np.float32),
        inflation_radius=np.asarray(inflation_radius, dtype=np.float32),
        distance=projected.astype(np.float32),
        inflated_distance=inflated.astype(np.float32),
        valid=projected_valid,
    )
    save_esdf_image(
        output_dir / "base_navigation_esdf.png",
        xs,
        ys,
        projected,
        projected_valid,
        f"Base navigation ESDF z=[{z_min:.2f}, {z_max:.2f}] m",
        max_abs_distance,
    )
    save_esdf_image(
        output_dir / "base_navigation_esdf_inflated.png",
        xs,
        ys,
        inflated,
        projected_valid,
        f"Inflated base ESDF radius={inflation_radius:.2f} m",
        max_abs_distance,
    )


def parse_args():
    parser = argparse.ArgumentParser(
        description="Project a 3D ESDF grid into a 2D base-navigation ESDF."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to esdf_grid.npz generated by export_nvblox_esdf.py.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output directory. Defaults to <input parent>/base_navigation.",
    )
    parser.add_argument("--z-min", type=float, default=0.05)
    parser.add_argument("--z-max", type=float, default=1.2)
    parser.add_argument("--inflation-radius", type=float, default=0.35)
    parser.add_argument("--max-abs-distance", type=float, default=0.5)
    return parser.parse_args()


def main():
    args = parse_args()
    input_path = Path(args.input)
    output_dir = (
        Path(args.output)
        if args.output is not None
        else input_path.parent / "base_navigation"
    )
    export_base_navigation_esdf(
        input_path,
        output_dir,
        args.z_min,
        args.z_max,
        args.inflation_radius,
        args.max_abs_distance,
    )
    print(f"Saved base-navigation ESDF to: {output_dir}", flush=True)


if __name__ == "__main__":
    main()
