"""Pure helpers for driving a WB-MPC controller from validated real state."""

from __future__ import annotations

import json
import math
import re
from dataclasses import dataclass
from typing import Mapping, Sequence

import numpy as np
from stretch_runtime.real_full_state import FULL_STATE_NAMES


@dataclass(frozen=True)
class WBMPCState:
    """Validated 11-position/11-velocity controller feedback."""

    position: np.ndarray
    velocity: np.ndarray


@dataclass(frozen=True)
class ForwardPrediction:
    """Bounded state trajectory generated by the controller's own model."""

    trajectory: np.ndarray
    bounded_acceleration: np.ndarray
    input_clipped: bool
    state_clipped: bool

    @property
    def position(self) -> np.ndarray:
        dimension = self.trajectory.shape[1] // 2
        return self.trajectory[-1, :dimension].copy()

    @property
    def velocity(self) -> np.ndarray:
        dimension = self.trajectory.shape[1] // 2
        return self.trajectory[-1, dimension:].copy()


@dataclass(frozen=True)
class WBMPCCommandEnvelope:
    """Atomic ROS transport contract for a time-bounded WB-MPC command."""

    generation: int
    valid: bool
    reason: str
    state_stamp: float | None
    plan_origin_monotonic: float | None
    valid_until_monotonic: float | None
    velocity: np.ndarray

    def __post_init__(self) -> None:
        velocity = np.asarray(self.velocity, dtype=float).reshape(-1).copy()
        if velocity.size != len(FULL_STATE_NAMES) or not np.all(np.isfinite(velocity)):
            raise ValueError(
                f"WB-MPC command velocity must contain {len(FULL_STATE_NAMES)} "
                "finite values"
            )
        generation = int(self.generation)
        if generation < 0:
            raise ValueError("WB-MPC command generation must be nonnegative")
        object.__setattr__(self, "generation", generation)
        object.__setattr__(self, "velocity", velocity)
        object.__setattr__(self, "reason", str(self.reason))
        if self.valid:
            values = (
                self.state_stamp,
                self.plan_origin_monotonic,
                self.valid_until_monotonic,
            )
            if generation == 0 or any(
                value is None or not math.isfinite(float(value)) for value in values
            ):
                raise ValueError(
                    "valid WB-MPC command needs a positive generation and finite times"
                )
            if float(self.valid_until_monotonic) < float(self.plan_origin_monotonic):
                raise ValueError("WB-MPC command validity interval is reversed")

    def is_current(self, now: float) -> bool:
        now = float(now)
        return bool(
            self.valid
            and math.isfinite(now)
            and now >= float(self.plan_origin_monotonic)
            and now <= float(self.valid_until_monotonic)
        )

    def to_json(self) -> str:
        return json.dumps(
            {
                "generation": self.generation,
                "valid": self.valid,
                "reason": self.reason,
                "state_stamp": self.state_stamp,
                "plan_origin_monotonic": self.plan_origin_monotonic,
                "valid_until_monotonic": self.valid_until_monotonic,
                "velocity": self.velocity.tolist(),
            },
            sort_keys=True,
            separators=(",", ":"),
        )

    @classmethod
    def from_json(cls, text: str) -> "WBMPCCommandEnvelope":
        try:
            data = json.loads(str(text))
        except json.JSONDecodeError as error:
            raise ValueError(f"invalid WB-MPC command JSON: {error}") from error
        if not isinstance(data, dict):
            raise ValueError("WB-MPC command JSON must be an object")
        required = {
            "generation",
            "valid",
            "reason",
            "state_stamp",
            "plan_origin_monotonic",
            "valid_until_monotonic",
            "velocity",
        }
        missing = sorted(required.difference(data))
        if missing:
            raise ValueError(f"WB-MPC command JSON is missing {missing}")
        if not isinstance(data["valid"], bool):
            raise ValueError("WB-MPC command valid field must be boolean")
        return cls(
            generation=data["generation"],
            valid=data["valid"],
            reason=data["reason"],
            state_stamp=data["state_stamp"],
            plan_origin_monotonic=data["plan_origin_monotonic"],
            valid_until_monotonic=data["valid_until_monotonic"],
            velocity=data["velocity"],
        )


def forward_predict_with_controller_model(
    robot,
    state: WBMPCState,
    acceleration: Sequence[float],
    duration: float,
    *,
    constraint_tolerance: float = 1.0e-2,
) -> ForwardPrediction:
    """Advance feedback with the exact dynamics and bounds used by WB-MPC.

    Full controller-sized steps call ``robot.ssSymMdl['fmdlk']`` directly. A
    fractional tail is discretized by the robot's own ``_discretizefmdl`` so
    nonholonomic dynamics and future model changes remain shared with acados.
    State/input boxes are read from the same robot model and projected after
    every step, matching the hard box constraints of the OCP.
    """

    position = np.asarray(state.position, dtype=float).reshape(-1)
    velocity = np.asarray(state.velocity, dtype=float).reshape(-1)
    dimension = int(robot.DoF)
    if position.size != dimension or velocity.size != dimension:
        raise ValueError("forward-prediction state dimension does not match controller")
    x = np.concatenate((position, velocity))
    u_requested = np.asarray(acceleration, dtype=float).reshape(-1)
    if u_requested.size != dimension:
        raise ValueError("forward-prediction input dimension does not match controller")
    duration = float(duration)
    tolerance = float(constraint_tolerance)
    if (
        not math.isfinite(duration)
        or duration < 0.0
        or not math.isfinite(tolerance)
        or tolerance < 0.0
        or not np.all(np.isfinite(x))
        or not np.all(np.isfinite(u_requested))
    ):
        raise ValueError("forward-prediction inputs must be finite and nonnegative")

    # MPCBase._setup_constraints consumes these exact arrays. Keeping the
    # deploy predictor on the symbolic model avoids a second limit source.
    model = robot.ssSymMdl
    lb_x = np.asarray(model["lb_x"], dtype=float).reshape(-1)
    ub_x = np.asarray(model["ub_x"], dtype=float).reshape(-1)
    lb_u = np.asarray(model["lb_u"], dtype=float).reshape(-1)
    ub_u = np.asarray(model["ub_u"], dtype=float).reshape(-1)
    if any(
        values.size != expected
        for values, expected in (
            (lb_x, 2 * dimension),
            (ub_x, 2 * dimension),
            (lb_u, dimension),
            (ub_u, dimension),
        )
    ):
        raise ValueError("controller model exposes inconsistent constraint dimensions")
    if np.any(x < lb_x - tolerance) or np.any(x > ub_x + tolerance):
        raise ValueError("measured state is outside controller bounds")

    bounded_u = np.clip(u_requested, lb_u, ub_u)
    input_clipped = not np.allclose(bounded_u, u_requested)
    clipped_x = np.clip(x, lb_x, ub_x)
    state_clipped = not np.allclose(clipped_x, x)
    x = clipped_x
    trajectory = [x.copy()]
    remaining = duration
    model_dt = float(robot.dt)
    if not math.isfinite(model_dt) or model_dt <= 0.0:
        raise ValueError("controller model dt must be positive and finite")
    while remaining > 1.0e-12:
        step = min(model_dt, remaining)
        if math.isclose(step, model_dt, rel_tol=0.0, abs_tol=1.0e-12):
            discrete_dynamics = model["fmdlk"]
        else:
            discrete_dynamics = robot._discretizefmdl(model, step)
        predicted = discrete_dynamics(x, bounded_u)
        predicted = np.asarray(predicted, dtype=float).reshape(-1)
        if predicted.size != 2 * dimension or not np.all(np.isfinite(predicted)):
            raise ValueError("controller dynamics produced an invalid predicted state")
        constrained = np.clip(predicted, lb_x, ub_x)
        state_clipped = state_clipped or not np.allclose(constrained, predicted)
        # A position box is unilateral: once projected onto a joint stop, do
        # not retain velocity that points farther outside the feasible set.
        for index in range(dimension):
            velocity_index = dimension + index
            if constrained[index] <= lb_x[index] and constrained[velocity_index] < 0.0:
                constrained[velocity_index] = 0.0
            if constrained[index] >= ub_x[index] and constrained[velocity_index] > 0.0:
                constrained[velocity_index] = 0.0
        x = constrained
        trajectory.append(x.copy())
        remaining -= step

    return ForwardPrediction(
        trajectory=np.asarray(trajectory),
        bounded_acceleration=bounded_u,
        input_clipped=input_clipped,
        state_clipped=state_clipped,
    )


def validate_wbmpc_state(
    names: Sequence[str],
    position: Sequence[float],
    velocity: Sequence[float],
) -> WBMPCState:
    """Validate and reorder a named state into the controller contract."""

    names = tuple(str(name) for name in names)
    if len(names) != len(set(names)):
        raise ValueError("WB-MPC state contains duplicate names")
    missing = [name for name in FULL_STATE_NAMES if name not in names]
    extra = [name for name in names if name not in FULL_STATE_NAMES]
    if missing or extra:
        raise ValueError(
            f"WB-MPC state names mismatch: missing={missing}, extra={extra}"
        )
    positions = np.asarray(position, dtype=float).reshape(-1)
    velocities = np.asarray(velocity, dtype=float).reshape(-1)
    if positions.size != len(names) or velocities.size != len(names):
        raise ValueError("WB-MPC state position/velocity lengths do not match names")
    if not np.all(np.isfinite(positions)) or not np.all(np.isfinite(velocities)):
        raise ValueError("WB-MPC state contains NaN or Inf")
    indices = [names.index(name) for name in FULL_STATE_NAMES]
    return WBMPCState(
        position=positions[indices].copy(),
        velocity=velocities[indices].copy(),
    )


def sample_acceleration_plan(
    plan: Sequence[Sequence[float]], elapsed: float, plan_dt: float
) -> np.ndarray:
    """Linearly sample an MPC acceleration plan, returning zero after its end."""

    values = np.asarray(plan, dtype=float)
    if values.ndim != 2 or values.shape[0] < 1:
        raise ValueError("acceleration plan must be a non-empty matrix")
    if not np.all(np.isfinite(values)):
        raise ValueError("acceleration plan contains NaN or Inf")
    elapsed = float(elapsed)
    plan_dt = float(plan_dt)
    if not math.isfinite(elapsed) or not math.isfinite(plan_dt) or plan_dt <= 0.0:
        raise ValueError("plan sampling time must be finite and plan_dt positive")
    if elapsed < 0.0:
        return values[0].copy()
    if elapsed > (values.shape[0] - 1) * plan_dt:
        return np.zeros(values.shape[1], dtype=float)
    scaled = elapsed / plan_dt
    lower = int(math.floor(scaled))
    if lower >= values.shape[0]:
        return np.zeros(values.shape[1], dtype=float)
    upper = lower + 1
    if upper >= values.shape[0]:
        return values[lower].copy()
    alpha = scaled - lower
    return (1.0 - alpha) * values[lower] + alpha * values[upper]


def sample_velocity_plan(
    plan: Sequence[Sequence[float]], elapsed: float, plan_dt: float
) -> np.ndarray:
    """Linearly sample the MPC state-velocity trajectory.

    Velocity targets are held at the terminal node. Plan validity is enforced
    independently by the real runner, so terminal hold avoids an artificial
    zero discontinuity if the configured validity window reaches the horizon.
    """

    values = np.asarray(plan, dtype=float)
    if values.ndim != 2 or values.shape[0] < 1:
        raise ValueError("velocity plan must be a non-empty matrix")
    if not np.all(np.isfinite(values)):
        raise ValueError("velocity plan contains NaN or Inf")
    elapsed = float(elapsed)
    plan_dt = float(plan_dt)
    if not math.isfinite(elapsed) or not math.isfinite(plan_dt) or plan_dt <= 0.0:
        raise ValueError("plan sampling time must be finite and plan_dt positive")
    if elapsed <= 0.0:
        return values[0].copy()
    scaled = elapsed / plan_dt
    lower = int(math.floor(scaled))
    if lower >= values.shape[0] - 1:
        return values[-1].copy()
    upper = lower + 1
    alpha = scaled - lower
    return (1.0 - alpha) * values[lower] + alpha * values[upper]


def controller_velocity_limits(
    controller_config: Mapping, expected_dimension: int
) -> tuple[np.ndarray, np.ndarray]:
    """Extract velocity bounds from the controller state-limit vector."""

    robot = controller_config["robot"]
    nq = int(robot["dims"]["q"])
    state_limits = robot["limits"]["state"]
    lower = np.asarray(
        [_parse_numeric_limit(value) for value in state_limits["lower"]],
        dtype=float,
    )[nq:]
    upper = np.asarray(
        [_parse_numeric_limit(value) for value in state_limits["upper"]],
        dtype=float,
    )[nq:]
    if lower.size != expected_dimension or upper.size != expected_dimension:
        raise ValueError("controller velocity limit dimension mismatch")
    if not np.all(np.isfinite(lower)) or not np.all(np.isfinite(upper)):
        raise ValueError("controller velocity limits contain NaN or Inf")
    if np.any(lower >= upper):
        raise ValueError("controller velocity limit interval is empty")
    return lower, upper


def _parse_numeric_limit(value) -> float:
    if not isinstance(value, str):
        return float(value)
    text = value.strip()
    if text in ("pi", "+pi"):
        return math.pi
    if text == "-pi":
        return -math.pi
    match = re.fullmatch(r"([+-]?(?:\d+(?:\.\d*)?|\.\d+))\.pi", text)
    if match is not None:
        return float(match.group(1)) * math.pi
    return float(text)
